# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81c69ac67bf01e164c09dbf1228107c4801aebe6e4c8e9afe513730659cef7e189c112594fe07a434d5f3114131d434cb3ffc8c3e4ad2bf4f5800cdb2042c038

test:
  secret_key_base: 42bc21b685e23b5ec9cc49c0b59ec1b9880adb893453c4c05f492d9d2937df12083ac745aed83792d9a6f4c2428f2fa91c8ea839f862ab8feb79a7d5f909c435

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
